global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'ADDRESS-SERVICE'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:9002
        labels:
          application: 'Address Service Application'
  - job_name: 'EMPLOYEE-SERVICE'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:9003
        labels:
          application: 'Employee Service Application'
