server:
  port: 9002

spring:
  application:
    name: ADDRESS-SERVICE
  zipkin:
    enabled: true
    service.name: address-service
    sender.type: web
    base-url: http://localhost:9411

  datasource:
    username: admin
    password: admin123
    url: jdbc:mysql://database-1.cmzaj8lsfcrp.us-east-2.rds.amazonaws.com:3306/addressService
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

    
management:
    endpoints:
        web:
            exposure:
                include: prometheus    
            
                  
  
