server:
  port: 9002

spring:
  application:
    name: ADDRESS-SERVICE
  zipkin:
    enabled: true
    service.name: address-service
    sender.type: web
    base-url: http://localhost:9411
     
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

logging:
   file: 
    name: C:/Users/ShiveshKumarSIDGloba/employee-address-project/log/address_service.log
    
management:
    endpoints:
        web:
            exposure:
                include: prometheus    
            
                  
  